services:
  baikal:
    image: ckulka/baikal:nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.baikal.tls=true
        - traefik.http.routers.baikal.tls.certresolver=production
        - traefik.http.routers.baikal.rule=Host(`baikal.kalny.net`)
        - traefik.http.services.baikal-baikal.loadbalancer.server.port=80
        - traefik.http.services.baikal-baikal.loadbalancer.healthcheck.path=/
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - proxy

volumes:
  config:
  data:

  
networks:
  proxy:
    external: true
